### ISSUE TITLE
Wrong version check

### ISSUE THREAD

**Issue by meiMingle** [DRSchlaubi/Intellij-GradleUpdater#15]
The plugin prompts me that gradle is out of date, but I am using the latest version of gradle. My idea version is 2021.2 .And the plugin version is 2.0.4.
![image](https://user-images.githubusercontent.com/39942874/130319028-f7c7d7ff-907c-4106-abd7-8eb963171b37.png)

**Comment by NyCodeGHG** [comment]
That's because Gradle released a new backport release. There's already a PR which fixes that issue. (#14)
But we have to wait a little, @DRSchlaubi had a very bad night with the Deutsche Bahn.

**Comment by meiMingle** [comment]
Why is it bad? Is it about COVID-19? I read the news in Germany now that the epidemic is more serious. How about you? Are you okay?

**Comment by NyCodeGHG** [comment]
His train got cancelled, and then he had to travel home much longer. In addition, he was already awake for a long time and then found nothing to drink. But about Covid-19, we are both fine. @DRSchlaubi is already fully vaccinated, and I have my 2nd vaccination in 2 weeks.

**Comment by DRSchlaubi** [comment]
I actually forgot to close this, this should be fixed
