### ISSUE TITLE
Dependency format conversion mistake

### ISSUE THREAD

**Issue by xuankaicat** [DRSchlaubi/Intellij-GradleUpdater#21]
```kotlin
manifest {
        attributes(
            Pair("Main-Class", "com.github.xuankaicat.MyLoaderKt")
        )
    }
// other code
}
```

Beacuse of i had checked auto change groovy to kotlin, this code will be converted:

```kotlin
manifest {
        attributes(
            Pair("Main-Class:com.github.xuankaicat.MyLoaderKt") // it is error
        )
    }
// other code
}
```

But i expected do nothing except copy this code block to other build.graadle.kts file at that memont.

**Comment by DRSchlaubi** [comment]
Does this still happen on the latest release?

**Comment by xuankaicat** [comment]
> Does this still happen on the latest release?

It won't happen again on the latest release.
