### ISSUE TITLE
Fix the logo

### ISSUE THREAD

**Issue by DRSchlaubi** [DRSchlaubi/Intellij-GradleUpdater#4]
The current one doesn't even have multiple colors and looks like shit

**Comment by Breefield** [comment]
Which file specifies the logo svg or raster?

**Comment by DRSchlaubi** [comment]
> Which file specifies the logo svg or raster?
> [EDIT] nevermind, [found it](https://github.com/DRSchlaubi/Intellij-GradleUpdater/blob/483e0642b8b9872d90c527109398d1143c90e3df/src/main/resources/META-INF/pluginIcon.svg)

The new logo doesn't need to look like the old one

**Comment by Breefield** [comment]
![logo](https://user-images.githubusercontent.com/188498/115637086-3ae04c80-a2c4-11eb-9d0e-572616ba51ae.png)
Followed the [brand guidelines](https://gradle.com/brand/), do you like?

**Comment by NyCodeGHG** [comment]
I like this

**Comment by DRSchlaubi** [comment]
Much better, I actually don't know what happened to the colors of the old one

**Comment by Breefield** [comment]
👍🏻
