### ISSUE TITLE
IntelliJ IDEA 2021.1 not supported

### ISSUE THREAD

**Issue by Crusader99** [DRSchlaubi/Intellij-GradleUpdater#8]
#### Issue description

Since the update to IntelliJ IDEA 2021.1 Build #IU-211.6693.111 this plugin seems no longer to be supported.

#### Steps to reproduce the issue
1. Update Intellij to the latest version
2. Check GradleUpdater is enabled in File -> Settings -> Plugins

#### What's the expected result?
Plugin is enabled and working.

#### What's the actual result?
Intellij shows a warning and plugin is not working.

#### Additional details / screenshot
![grafik](https://user-images.githubusercontent.com/26634807/114798591-fb7ea100-9d95-11eb-9216-9b81a254edee.png)

**Comment by DRSchlaubi** [comment]
That's a problem, this will be fixed together with the next feature release

**Comment by DRSchlaubi** [comment]
There is an EAP release also targetting 2021.1: https://github.com/DRSchlaubi/Intellij-GradleUpdater/pull/6#issuecomment-826338782
